<a href="https://colab.research.google.com/github/MuchnikJansyG/AnalisisDatosMasivos1/blob/main/Actividad1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
# Instalación de librerías si no están presentes
if(!require(tidyverse)) install.packages("tidyverse")
if(!require(ggpubr)) install.packages("ggpubr")

library(tidyverse)
library(ggpubr)

Loading required package: tidyverse

── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.2.0     ✔ readr     2.2.0
✔ forcats   1.0.1     ✔ stringr   1.6.0
✔ ggplot2   4.0.2     ✔ tibble    3.3.1
✔ lubridate 1.9.5     ✔ tidyr     1.3.2
✔ purrr     1.2.1
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors
Loading required package: ggpubr

Warning message in library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE, :
“there is no package called ‘ggpubr’”
Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

also installing the dependencies ‘colorspace’, ‘fracdiff’, ‘lmtest’, ‘timeDate’, ‘urca’, ‘zoo’, ‘RcppArmadillo’, ‘Deriv’, ‘forecast’, ‘microbenchmark’, ‘rbibutils’, ‘numDeriv’, ‘doBy’, ‘SparseM’, ‘MatrixModels’, ‘Rdpack’, ‘minqa’, ‘nloptr’, ‘reformulas’, ‘RcppEigen’, ‘carData’, ‘abind’, ‘Formula’, ‘pbkrtest’, ‘quantreg’, ‘lme4’, ‘corrplot’, ‘car’, ‘ggrepel’, ‘ggsci’, ‘cowplot’, ‘ggsignif’, ‘gridExtra’, ‘polynom’, ‘rstatix’

In [5]:
list.files("/content")

[1] "sample_data"                   "StudentPerformanceFactors.csv"

In [9]:
# Cargar el dataset (asegúrate de haber subido el archivo a Colab)
student <- read.csv("StudentPerformanceFactors.csv")
head(student, 5)

  Hours_Studied Attendance Parental_Involvement Access_to_Resources
1 23            84         Low                  High
2 19            64         Low                  Medium
3 24            98         Medium               Medium
4 29            89         Low                  Medium
5 19            92         Medium               Medium
  Extracurricular_Activities Sleep_Hours Previous_Scores Motivation_Level
1 No                         7           73              Low
2 No                         8           59              Low
3 Yes                        7           91              Medium
4 Yes                        8           98              Medium
5 Yes                        6           65              Medium
  Internet_Access Tutoring_Sessions Family_Income Teacher_Quality School_Type
1 Yes             0                 Low           Medium          Public
2 Yes             2                 Medium        Medium          Public
3 Yes             2                 Medium        Medium          Public
4 Yes             1                 Medium        Medium          Public
5 Yes             3                 Medium        High            Public
  Peer_Influence Physical_Activity Learning_Disabilities
1 Positive       3                 No
2 Negative       4                 No
3 Neutral        4                 No
4 Negative       4                 No
5 Neutral        4                 No
  Parental_Education_Level Distance_from_Home Gender Exam_Score
1 High School              Near               Male   67
2 College                  Moderate           Female 61
3 Postgraduate             Near               Male   74
4 High School              Moderate           Male   71
5 College                  Near               Female 70

In [10]:
str(student)  # Muestra la estructura y tipos de datos
summary(student) # Muestra un resumen estadístico (útil para detectar valores extraños)

'data.frame':	6607 obs. of  20 variables:
 $ Hours_Studied             : int  23 19 24 29 19 19 29 25 17 23 ...
 $ Attendance                : int  84 64 98 89 92 88 84 78 94 98 ...
 $ Parental_Involvement      : chr  "Low" "Low" "Medium" "Low" ...
 $ Access_to_Resources       : chr  "High" "Medium" "Medium" "Medium" ...
 $ Extracurricular_Activities: chr  "No" "No" "Yes" "Yes" ...
 $ Sleep_Hours               : int  7 8 7 8 6 8 7 6 6 8 ...
 $ Previous_Scores           : int  73 59 91 98 65 89 68 50 80 71 ...
 $ Motivation_Level          : chr  "Low" "Low" "Medium" "Medium" ...
 $ Internet_Access           : chr  "Yes" "Yes" "Yes" "Yes" ...
 $ Tutoring_Sessions         : int  0 2 2 1 3 3 1 1 0 0 ...
 $ Family_Income             : chr  "Low" "Medium" "Medium" "Medium" ...
 $ Teacher_Quality           : chr  "Medium" "Medium" "Medium" "Medium" ...
 $ School_Type               : chr  "Public" "Public" "Public" "Public" ...
 $ Peer_Influence            : chr  "Positive" "Negative" "Neutral" "Negative" ...
 $ Physical_Activity         : int  3 4 4 4 4 3 2 2 1 5 ...
 $ Learning_Disabilities     : chr  "No" "No" "No" "No" ...
 $ Parental_Education_Level  : chr  "High School" "College" "Postgraduate" "High School" ...
 $ Distance_from_Home        : chr  "Near" "Moderate" "Near" "Moderate" ...
 $ Gender                    : chr  "Male" "Female" "Male" "Male" ...
 $ Exam_Score                : int  67 61 74 71 70 71 67 66 69 72 ...

 Hours_Studied     Attendance     Parental_Involvement Access_to_Resources
 Min.   : 1.00   Min.   : 60.00   Length:6607          Length:6607
 1st Qu.:16.00   1st Qu.: 70.00   Class :character     Class :character
 Median :20.00   Median : 80.00   Mode  :character     Mode  :character
 Mean   :19.98   Mean   : 79.98
 3rd Qu.:24.00   3rd Qu.: 90.00
 Max.   :44.00   Max.   :100.00
 Extracurricular_Activities  Sleep_Hours     Previous_Scores
 Length:6607                Min.   : 4.000   Min.   : 50.00
 Class :character           1st Qu.: 6.000   1st Qu.: 63.00
 Mode  :character           Median : 7.000   Median : 75.00
                            Mean   : 7.029   Mean   : 75.07
                            3rd Qu.: 8.000   3rd Qu.: 88.00
                            Max.   :10.000   Max.   :100.00
 Motivation_Level   Internet_Access    Tutoring_Sessions Family_Income
 Length:6607        Length:6607        Min.   :0.000     Length:6607
 Class :character   Class :character   1st Qu.:1.000     Class :character
 Mode  :character   Mode  :character   Median :1.000     Mode  :character
                                       Mean   :1.494
                                       3rd Qu.:2.000
                                       Max.   :8.000
 Teacher_Quality    School_Type        Peer_Influence     Physical_Activity
 Length:6607        Length:6607        Length:6607        Min.   :0.000
 Class :character   Class :character   Class :character   1st Qu.:2.000
 Mode  :character   Mode  :character   Mode  :character   Median :3.000
                                                          Mean   :2.968
                                                          3rd Qu.:4.000
                                                          Max.   :6.000
 Learning_Disabilities Parental_Education_Level Distance_from_Home
 Length:6607           Length:6607              Length:6607
 Class :character      Class :character         Class :character
 Mode  :character      Mode  :character         Mode  :character



    Gender            Exam_Score
 Length:6607        Min.   : 55.00
 Class :character   1st Qu.: 65.00
 Mode  :character   Median : 67.00
                    Mean   : 67.24
                    3rd Qu.: 69.00
                    Max.   :101.00

In [11]:
library(dplyr)

# 1. Aseguramos que el objeto 'student' exista y aplicamos las transformaciones
student_clean <- student %>%
  mutate(
    # Convertir variables categóricas de 'chr' a 'factor'
    Parental_Involvement = as.factor(Parental_Involvement),
    Access_to_Resources = as.factor(Access_to_Resources),
    Extracurricular_Activities = as.factor(Extracurricular_Activities),
    Motivation_Level = as.factor(Motivation_Level),
    Internet_Access = as.factor(Internet_Access),
    Family_Income = as.factor(Family_Income),
    Teacher_Quality = as.factor(Teacher_Quality),
    School_Type = as.factor(School_Type),
    Peer_Influence = as.factor(Peer_Influence),
    Learning_Disabilities = as.factor(Learning_Disabilities),
    Parental_Education_Level = as.factor(Parental_Education_Level),
    Distance_from_Home = as.factor(Distance_from_Home),
    Gender = as.factor(Gender),

    # Asegurar que las numéricas sean tratadas como tales
    # (Útil si alguna se leyó mal inicialmente)
    Hours_Studied = as.integer(Hours_Studied),
    Attendance = as.integer(Attendance),
    Sleep_Hours = as.integer(Sleep_Hours),
    Previous_Scores = as.integer(Previous_Scores),
    Exam_Score = as.integer(Exam_Score)
  )

# 2. Verificar que no haya introducido NAs durante la conversión
# Si aparecen NAs, significa que había texto en columnas numéricas
colSums(is.na(student_clean))

# 3. Ver el resultado final
str(student_clean)

             Hours_Studied                 Attendance
                         0                          0
      Parental_Involvement        Access_to_Resources
                         0                          0
Extracurricular_Activities                Sleep_Hours
                         0                          0
           Previous_Scores           Motivation_Level
                         0                          0
           Internet_Access          Tutoring_Sessions
                         0                          0
             Family_Income            Teacher_Quality
                         0                          0
               School_Type             Peer_Influence
                         0                          0
         Physical_Activity      Learning_Disabilities
                         0                          0
  Parental_Education_Level         Distance_from_Home
                         0                          0
                    Gender                 Exam_Score
                         0                          0

'data.frame':	6607 obs. of  20 variables:
 $ Hours_Studied             : int  23 19 24 29 19 19 29 25 17 23 ...
 $ Attendance                : int  84 64 98 89 92 88 84 78 94 98 ...
 $ Parental_Involvement      : Factor w/ 3 levels "High","Low","Medium": 2 2 3 2 3 3 3 2 3 3 ...
 $ Access_to_Resources       : Factor w/ 3 levels "High","Low","Medium": 1 3 3 3 3 3 2 1 1 3 ...
 $ Extracurricular_Activities: Factor w/ 2 levels "No","Yes": 1 1 2 2 2 2 2 2 1 2 ...
 $ Sleep_Hours               : int  7 8 7 8 6 8 7 6 6 8 ...
 $ Previous_Scores           : int  73 59 91 98 65 89 68 50 80 71 ...
 $ Motivation_Level          : Factor w/ 3 levels "High","Low","Medium": 2 2 3 3 3 3 2 3 1 3 ...
 $ Internet_Access           : Factor w/ 2 levels "No","Yes": 2 2 2 2 2 2 2 2 2 2 ...
 $ Tutoring_Sessions         : int  0 2 2 1 3 3 1 1 0 0 ...
 $ Family_Income             : Factor w/ 3 levels "High","Low","Medium": 2 3 3 3 3 3 2 1 3 1 ...
 $ Teacher_Quality           : Factor w/ 4 levels "","High","Low",..: 4 4 4 4 2 4 4 2 3 2 ...
 $ School_Type               : Factor w/ 2 levels "Private","Public": 2 2 2 2 2 2 1 2 1 2 ...
 $ Peer_Influence            : Factor w/ 3 levels "Negative","Neutral",..: 3 1 2 1 2 3 2 1 2 3 ...
 $ Physical_Activity         : int  3 4 4 4 4 3 2 2 1 5 ...
 $ Learning_Disabilities     : Factor w/ 2 levels "No","Yes": 1 1 1 1 1 1 1 1 1 1 ...
 $ Parental_Education_Level  : Factor w/ 4 levels "","College","High School",..: 3 2 4 3 2 4 3 3 2 3 ...
 $ Distance_from_Home        : Factor w/ 4 levels "","Far","Moderate",..: 4 3 4 3 4 4 3 2 4 3 ...
 $ Gender                    : Factor w/ 2 levels "Female","Male": 2 1 2 2 1 2 2 2 2 2 ...
 $ Exam_Score                : int  67 61 74 71 70 71 67 66 69 72 ...

In [12]:
# Limitar el score máximo a 100 si es necesario
student_clean$Exam_Score[student_clean$Exam_Score > 100] <- 100

In [16]:
#Columnas que tienen un orden lógico (Low < Medium < High) se convirtieron en factores ordenados
#lo que ayudará mucho en tus futuros modelos ya que definimos el orden lógico una sola vez.
niveles_ordenados <- c("Low", "Medium", "High")

student_clean <- student_clean %>%
  mutate(across(
    .cols = c(Motivation_Level, Parental_Involvement, Teacher_Quality, Access_to_Resources),
    .fns = ~ factor(.x, levels = niveles_ordenados, ordered = TRUE)
  ))

# Verificar el resultado
#str(student_clean[c("Motivation_Level", "Parental_Involvement", "Teacher_Quality","Access_to_Resources")])
head(student_clean, 5)

  Hours_Studied Attendance Parental_Involvement Access_to_Resources
1 23            84         Low                  High
2 19            64         Low                  Medium
3 24            98         Medium               Medium
4 29            89         Low                  Medium
5 19            92         Medium               Medium
  Extracurricular_Activities Sleep_Hours Previous_Scores Motivation_Level
1 No                         7           73              Low
2 No                         8           59              Low
3 Yes                        7           91              Medium
4 Yes                        8           98              Medium
5 Yes                        6           65              Medium
  Internet_Access Tutoring_Sessions Family_Income Teacher_Quality School_Type
1 Yes             0                 Low           Medium          Public
2 Yes             2                 Medium        Medium          Public
3 Yes             2                 Medium        Medium          Public
4 Yes             1                 Medium        Medium          Public
5 Yes             3                 Medium        High            Public
  Peer_Influence Physical_Activity Learning_Disabilities
1 Positive       3                 No
2 Negative       4                 No
3 Neutral        4                 No
4 Negative       4                 No
5 Neutral        4                 No
  Parental_Education_Level Distance_from_Home Gender Exam_Score
1 High School              Near               Male   67
2 College                  Moderate           Female 61
3 Postgraduate             Near               Male   74
4 High School              Moderate           Male   71
5 College                  Near               Female 70

In [14]:
head(student_clean, 5)

  Hours_Studied Attendance Parental_Involvement Access_to_Resources
1 23            84         Low                  High
2 19            64         Low                  Medium
3 24            98         Medium               Medium
4 29            89         Low                  Medium
5 19            92         Medium               Medium
  Extracurricular_Activities Sleep_Hours Previous_Scores Motivation_Level
1 No                         7           73              Low
2 No                         8           59              Low
3 Yes                        7           91              Medium
4 Yes                        8           98              Medium
5 Yes                        6           65              Medium
  Internet_Access Tutoring_Sessions Family_Income Teacher_Quality School_Type
1 Yes             0                 Low           Medium          Public
2 Yes             2                 Medium        Medium          Public
3 Yes             2                 Medium        Medium          Public
4 Yes             1                 Medium        Medium          Public
5 Yes             3                 Medium        High            Public
  Peer_Influence Physical_Activity Learning_Disabilities
1 Positive       3                 No
2 Negative       4                 No
3 Neutral        4                 No
4 Negative       4                 No
5 Neutral        4                 No
  Parental_Education_Level Distance_from_Home Gender Exam_Score
1 High School              Near               Male   67
2 College                  Moderate           Female 61
3 Postgraduate             Near               Male   74
4 High School              Moderate           Male   71
5 College                  Near               Female 70

In [18]:

# Filtramos las filas donde el campo es exactamente un texto vacío ""
registros_vacios <- student_clean %>%
  filter(Parental_Education_Level == "" | is.na(Parental_Education_Level))

# Ver los primeros resultados y el conteo total
print(paste("Total de registros vacíos:", nrow(registros_vacios)))
head(registros_vacios)

[1] "Total de registros vacíos: 90"

  Hours_Studied Attendance Parental_Involvement Access_to_Resources
1 15            87         Low                  Medium
2 21            65         High                 High
3 21            91         High                 Medium
4 26            94         High                 Medium
5 23            85         High                 Low
6 20            81         Medium               Low
  Extracurricular_Activities Sleep_Hours Previous_Scores Motivation_Level
1 No                          4          54              Medium
2 No                          7          88              Low
3 No                          9          74              Medium
4 Yes                        10          54              Low
5 Yes                         6          59              Low
6 Yes                         6          53              Low
  Internet_Access Tutoring_Sessions Family_Income Teacher_Quality School_Type
1 Yes             1                 Medium        Medium          Public
2 Yes             2                 Low           Medium          Private
3 Yes             2                 Low           Low             Private
4 Yes             2                 High          Medium          Public
5 Yes             1                 Medium        Medium          Public
6 Yes             0                 Medium        Low             Public
  Peer_Influence Physical_Activity Learning_Disabilities
1 Neutral        6                 No
2 Neutral        1                 No
3 Negative       2                 No
4 Neutral        5                 No
5 Negative       1                 No
6 Neutral        4                 No
  Parental_Education_Level Distance_from_Home Gender Exam_Score
1 NA                       Moderate           Male   65
2 NA                       Near               Male   65
3 NA                       Near               Female 69
4 NA                       Near               Male   73
5 NA                       Near               Male   68
6 NA                       Far                Female 63